FROM --platform=linux/amd64 golang:alpine AS build
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -a -installsuffix cgo -o gobadge

FROM scratch
COPY --from=build gobadge gobadge
CMD ["gobadge"]