FROM --platform=$BUILDPLATFORM golang:alpine AS build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-w -s" -a -installsuffix cgo -o gobadge
ARG TARGETPLATFORM
ARG BUILDPLATFORM

FROM scratch
COPY --from=build gobadge gobadge
CMD ["gobadge"]