FROM --platform=$BUILDPLATFORM golang:alpine AS build
RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM" > /log
# RUN cat log
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -a -installsuffix cgo -o gobadge
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG PLATFORM
ARG ARCH
ARG ARCH_VERSION

FROM scratch
COPY --from=build gobadge gobadge
CMD ["gobadge"]