name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      - name: build arm7
        run: |
          docker build -t ${{ github.repository }}:manifest-latest-arm7 \
          -f Dockerfile.arm.7 .
          docker push ${{ github.repository }}:manifest-latest-arm7
      - name: build amd64
        run: |
          docker build -t ${{ github.repository }}:manifest-latest-amd64 \
          -f Dockerfile.arm64 .
          docker push ${{ github.repository }}:manifest-latest-amd64
      - name: build arm64
        run: |
          docker build -t ${{ github.repository }}:manifest-latest-arm64 \
          -f Dockerfile.amd64 .
          docker push ${{ github.repository }}:manifest-latest-arm64
      - name: push the image
        run: |
          echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl restart docker
          docker version -f '{{.Server.Experimental}}'
          docker manifest create \
          ${{ github.repository }}:latest \
          --amend ${{ github.repository }}:manifest-latest-amd64 \
          --amend ${{ github.repository }}:manifest-latest-arm7 \
          --amend ${{ github.repository }}:manifest-latest-arm64
          docker manifest push ${{ github.repository }}:latest