name: ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      - name: build arm7
        run: |
          docker build -t ${{ github.repository }}:latest \
          --build-arg PLATFORM=linux --build-arg ARCH=arm --build-arg ARCH_VERSION=v7 \
          --platform linux/arm/v7 -f Dockerfile.arm.7 .
      - name: build amd64
        run: |
          docker build -t ${{ github.repository }}:latest \
          --build-arg PLATFORM=linux --build-arg ARCH=amd64 \
          --platform linux/amd64 -f Dockerfile.arm64 .
      - name: build arm64
        run: |
          docker build -t ${{ github.repository }}:latest \
          --build-arg PLATFORM=linux --build-arg ARCH=arm64 \
          --platform linux/arm64 -f Dockerfile.amd64 .
      - name: push the image
        run: docker push ${{ github.repository }}:latest